spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teams
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    format-sql: true

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      host: localhost
      port: 6379
      database: teams-redis-cache
      password: redis
      timeout: 10000

  flyway:
    locations: classpath:db/migration
    baseline-version: 0
    baseline-description: Initial schema
    baseline-on-migrate: true