spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/issues
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      host: localhost
      port: 6381
      database: issues-redis-cache
      password: redis
      timeout: 10000

  flyway:
    locations: classpath:db/migration
    baseline-version: 0
    baseline-description: Initial schema
    baseline-on-migrate: true