spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/issues
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    locations: classpath:db/migration
    baseline-version: 0
    baseline-description: Initial schema
    baseline-on-migrate: true