spring:
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: boards
      username: root
      password: mongo
      authentication-database: admin
      uuid-representation: standard
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
api:
  team:
    url: http://localhost:8080/api/teams
  issue:
    url: http://localhost:8081/api/issues