spring:
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: boards
      username: root
      password: mongo
      authentication-database: admin
      uuid-representation: standard

  cache:
    type: redis
    redis:
      time-to-live: 3600000
      host: localhost
      port: 6379
      database: teams-redis-cache
      password: redis
      timeout: 10000
api:
  teams:
    url: http://localhost:8080/api/teams
  issues:
    url: http://localhost:8081/api/issues