server:
  port: 8082
  servlet:
    context-path: /api
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

management:
  health:
    rabbit:
      enabled: true
    redis:
      enabled: true
  endpoint:
    health:
      show-details: always