spring:
  rabbitmq:
    username: rabbitmq
    password: rabbitmq
    host: localhost
    port: 5672
  data:
    mongodb:
      host: localhost
      port: 27017
      database: boards
      username: root
      password: mongo
      authentication-database: admin