spring:
  rabbitmq:
    listener:
      direct:
        auto-startup: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: boards
      username: test
      password: test
      authentication-database: admin
      uuid-representation: standard

management:
  health:
    rabbit:
      enabled: false