name: CI

on:
  push:
    branches:
        - '*'
  pull_request:
    branches: [ main ]


jobs:
  build:
    strategy:
      matrix:
        project:
          - 'teams-api'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew build -x test
        working-directory: ${{ matrix.project }}

  test:
    needs: [ build ]
    strategy:
      matrix:
        project:
          - 'teams-api'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run tests
        run: ./gradlew test
        working-directory: ${{ matrix.project }}
